# Generated by Django 5.2 on 2025-05-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Business', 'Business'), ('Politics', 'Politics'), ('Entertainment', 'Entertainment'), ('Economy', 'Economy'), ('Lifestyle', 'Lifestyle'), ('Web Development', 'Web Development')], max_length=255, null=True),
        ),
    ]
